feat: add functionality for "Community" dropdown and minor styling changes
flybywiresim/website pull request #100
Opened 2021-02-14 23:06 UTC by ErickSharp

Before:
![image](https://user-images.githubusercontent.com/30361843/107891830-b699d380-6ee6-11eb-94d6-235232a83d6f.png)
![image](https://user-images.githubusercontent.com/30361843/107891840-bd284b00-6ee6-11eb-9538-7e251172a427.png)
After:
![image](https://user-images.githubusercontent.com/30361843/107891860-e8ab3580-6ee6-11eb-87dd-4ec2a6385750.png)
![image](https://user-images.githubusercontent.com/30361843/107891867-f19c0700-6ee6-11eb-9737-37dc2cc40163.png)

2021-02-15 21:08 UTC, NathanInnes commented
Please rebase to resolve conflicts.

2021-02-15 23:55 UTC, ErickSharp commented
> Please rebase to resolve conflicts.

Just fixed the conflicts.

2021-02-15 23:59 UTC, ErickSharp commented
Hold off on pulling, there are still some issues.

2021-02-16 00:09 UTC, ErickSharp commented
All conflicts and issues are fixed now, ready for merge

2021-02-16 01:05 UTC, Benjozork requested changes

2021-02-16 01:05 UTC, Benjozork commented
forgot to submit this

2021-02-16 01:23 UTC, ErickSharp commented on src/components/app/Dropdown.tsx
> +                    {/*Heroicon name: solid/chevron-down*/}
removed comment

2021-02-16 01:24 UTC, ErickSharp commented on src/components/app/NavBar.tsx
> +                            <DropdownItem name="Development Blog" link="/blog" />
Was discussed with falcon and sabes, is easily able to be changed in the future.

2021-02-16 01:29 UTC, NathanInnes commented on src/components/utils/Dropdown.tsx
> +                    {/*Heroicon name: solid/chevron-down*/}
One comment left to remove

2021-02-16 01:33 UTC, ErickSharp commented on src/components/utils/Dropdown.tsx
> +                    {/*Heroicon name: solid/chevron-down*/}
sorry about that, fixed

2021-02-16 01:41 UTC, NathanInnes commented
On mobile is also broken, if you can fix it that would be great, hmu if you want help with it 
![image](https://user-images.githubusercontent.com/18389085/108008372-20ee6900-6ff8-11eb-86bf-c8cda4dfe5a1.png)

2021-02-16 03:31 UTC, NathanInnes commented
Fixed issue for mobile and desktop.

Desktop:
![image](https://user-images.githubusercontent.com/18389085/108014931-f5bf4600-7006-11eb-96d3-897eca6fa8d6.png)

Mobile: 
![image](https://user-images.githubusercontent.com/18389085/108015123-64040880-7007-11eb-9e29-a2768df77b65.png)

2021-02-16 03:31 UTC, NathanInnes approved these changes

2021-02-16 03:31 UTC, merged