feat: projects page
flybywiresim/website pull request #124
Opened 2021-03-06 05:11 UTC by armankir

I added a basic layout and design for the projects page.

2021-03-07 11:13 UTC, ErickSharp commented
I have a branch set up to fix the scaling issues with the extended features section. Can't request changes on here so I might just open another pull request after this is merged. Message me on Discord if you want to get the code to put it in this single PR!

2021-03-07 11:18 UTC, ErickSharp commented
I have a PR open to change the download section to be for the installer like you asked, we are going to have to figure something out as to how we will include the installer and the direct download links. I have something in mind like making a very thin bar for the direct downloads but above that is the Installer component.

2021-03-08 02:22 UTC, ErickSharp commented
I like the idea and look of the plane, just with some minor tweaking. One thing that I have noticed is that the plane doesn't load in at once when you load up the page, it loads in a bit after.

2021-03-08 02:26 UTC, armankir commented
> I like the idea and look of the plane, just with some minor tweaking. One thing that I have noticed is that the plane doesn't load in at once when you load up the page, it loads in a bit after.

Can't do anything about that. What kind of tweaking do you want? Request the changes.

2021-03-08 03:38 UTC, ErickSharp requested changes

2021-03-08 03:38 UTC, ErickSharp commented on src/components/projects/A32NX.tsx
> +        <img draggable="false" className="absolute -right-1/3 transform scale-150 opacity-30 select-none" src={a32nx_wireframe} alt="" />
```suggestion
        <img draggable="false" className="absolute hidden md:block right-96 md:-right-1/3 transform scale-150 opacity-40 select-none" src={a32nx_wireframe} alt="" />
```
Make the wireframe hidden on mobile

2021-03-08 04:13 UTC, ErickSharp requested changes
oops, should be block and not visible; my bad.

2021-03-08 04:13 UTC, ErickSharp commented on src/components/projects/A32NX.tsx
> +        <img draggable="false" className="absolute hidden md:visible -right-1/3 transform scale-150 opacity-30 select-none" src={a32nx_wireframe} alt="" />
```suggestion
        <img draggable="false" className="absolute hidden md:block -right-1/3 transform scale-150 opacity-30 select-none" src={a32nx_wireframe} alt="" />
```

2021-03-08 13:44 UTC, ErickSharp commented
There’s an issue with the scaling for the extended features I didn’t notice, it’s pretty minor and I have a fix for it. It changes it to 3 per row at medium but then you will have 2 at the very bottom without a third one to complete the row so I don’t know if you would like the look of that.

2021-03-08 15:21 UTC, NathanInnes approved these changes

2021-03-08 15:21 UTC, merged