feat: make the mobile navbar close when you click on a link
flybywiresim/website pull request #223
Opened 2021-05-22 02:57 UTC by ErickSharp

## Summary of changes
make the mobile navbar close when you click on a link 🦅🦅😏✅✅

## Screenshots(if applicable)
- [x] all of the above 
- [x] ✅✅

2021-05-22 03:00 UTC, scoopscode commented
Works on mobile correctly, using iOS!

2021-05-22 21:32 UTC, NathanInnes requested changes

2021-05-22 21:32 UTC, NathanInnes commented on src/components/utils/NavBar.tsx
> +        <div className="flex flex-col fixed top-0 left-0 right-0 mx-auto z-50">
Most top level tag should be ```nav```

2021-05-22 22:51 UTC, ErickSharp commented on src/components/utils/NavBar.tsx
> +        <div className="flex flex-col fixed top-0 left-0 right-0 mx-auto z-50">
fixed

2021-05-23 14:57 UTC, NathanInnes approved these changes

2021-05-23 14:57 UTC, merged