blog: hydraulics notam
flybywiresim/website pull request #387
Opened 2022-02-18 13:07 UTC by Valastiri

## Summary of changes
< Provide a summary of the changes in this pull request, ensure that all changes are explained. >
3rd installment of February NOTAMs featuring hydraulics. 

### TODO

- [x] Final Proof
- [x] New Featured Image
- [x] Uploaded Video Media
- [x] Marketing Release

2022-02-18 13:24 UTC, crocket63 commented
Soon to come part has already got to master, so I'll try to update this part with the latest stuff we did for hydraulics

2022-02-22 13:31 UTC, crocket63 commented on src/posts/hydraulics-update-2022.md
> +What’s up in the hydraulics department? Maybe you haven't noticed, but lately some features have already made their way in into the development version.
"way in into the"  -> into or in but not both I guess :)

2022-02-22 13:35 UTC, crocket63 commented on src/posts/hydraulics-update-2022.md
> +Even in with this early version, we are already simulating the fact that in certain speed/pitch demand conditions, the elevator is commanded by all actuators instead of "one slave/one master" actuato
wether "in" or "with"

2022-02-24 16:10 UTC, Benjozork requested changes

2022-02-24 16:10 UTC, Benjozork commented on src/posts/hydraulics-update-2022.md
> +### Physical Based PTU
```suggestion
### Physics Based PTU
```

2022-02-25 13:12 UTC, merged